---
- name: Provision cluster resources
  openshift_provision:
    action: "{{ provision_action }}"
    patch_type: >-
      {{
      item | json_query('metadata.annotations."openshift-provision/patch-type"')
      | default(item.patch_type, true)
      | default('strategic', true)
      }}
    connection:
      oc_cmd: "{{ oc_cmd }}"
    resource: "{{ item }}"
    generate_resources: "{{ generate_resources }}"
  loop: "{{ resource_list }}"
  vars:
    provision_action: >-
      {{
      item | json_query('metadata.annotations."openshift-provision/action"')
      | default(item.action, true)
      | default('apply', true)
      }}
  when: provision_action != 'ignore'
  register: provision
  changed_when: >-
    provision | record_change_provision(change_record)
  ignore_errors: True
- name: Record new failures
  set_fact:
    provision_failures: "{{ provision_failures + [record] }}"
  loop: "{{ provision.results }}"
  vars:
    record:
      failed: true
      resource: >-
        {{ item.invocation.module_args.resource
           if (item.invocation.module_args.resource | default({})) else
           (item.resource
              if item.resource | default({}) else
              (item.item
                 if item.item | default({}) else
                 {})) }}
      invocation: "{{ {'module_args': item.invocation.module_args | default({}, true)} }}"
      msg: "{{ item.msg | default('', true) }}"
  when: item.failed | default(false)
- set_fact:
    provision_failures_skipped: "{{ provision_failures_skipped + [provision] }}"
  when: "'results' not in provision"
