---
- name: Grant user cluster role {{ cluster_role_binding.role }}
  command: >-
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy add-cluster-role-to-user
    {{ cluster_role_binding.role }} {{ item }}
    {% if openshift_provision_openshift_version is version_compare('v3.9', '>=') %}
    --rolebinding-name={{ cluster_role_binding.role }}
    {% endif %}
  loop: "{{ cluster_role_binding.users | default([]) }}"
  when: >-
    (
      item is match('system:serviceaccount:') and
      {
        'kind': 'ServiceAccount',
        'name': item.split(':')[3],
        'namespace': item.split(':')[2]
      } not in current_cluster_role_service_accounts
    ) or (
      item is not match('system:serviceaccount:') and
      item not in current_cluster_role_users
    )
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Grant group cluster role {{ cluster_role_binding.role }}
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy add-cluster-role-to-group {{ cluster_role_binding.role }} {{ item }}
  loop: "{{ cluster_role_binding.groups | default([]) }}"
  when: >
    item not in current_cluster_role_groups
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Remove unlisted users from cluster role {{ cluster_role_binding.role }}
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy remove-cluster-role-from-user
    {{ cluster_role_binding.role }} {{ item }}
  loop: "{{ current_cluster_role_users }}"
  when: >
    ( cluster_role_binding.remove_unlisted | default(false) | bool or
      cluster_role_binding.remove_unlisted_users | default(false) | bool ) and
    item not in cluster_role_binding.users | default([])
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Remove unlisted service accounts from cluster role {{ cluster_role_binding.role }}
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy remove-cluster-role-from-user
    {{ cluster_role_binding.role }} {{ service_account_string }}
  loop: "{{ current_cluster_role_service_accounts }}"
  vars:
    service_account_string: >-
      system:serviceaccount:{{ item.namespace }}:{{ item.name }}
  when: >
    ( cluster_role_binding.remove_unlisted | default(false) | bool or
      cluster_role_binding.remove_unlisted_users | default(false) | bool ) and
    service_account_string not in cluster_role_binding.users | default([])
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Remove unlisted groups from cluster role {{ cluster_role_binding.role }}
  command: >
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy remove-cluster-role-from-group {{ cluster_role_binding.role }} {{ item }}
  loop: "{{ current_cluster_role_groups }}"
  when: >
    ( cluster_role_binding.remove_unlisted | default(false) | bool or
      cluster_role_binding.remove_unlisted_groups | default(false) | bool ) and
    item not in cluster_role_binding.groups | default([])
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)
