- name: Get groups with role {{ role }} in {{ project.name }}
  command: >
    oc get rolebinding {{ role | quote }} -n {{ project.name }}
    --template '{{ '{{ range .groupNames }}{{ . }}{{ "\n" }}{{ end }}' }}'
  changed_when: false
  failed_when: false
  register: get_groups_with_role

- name: Grant {{ role }} to {{ group }} in project {{ project.name }}
  command: >
    oc adm policy add-role-to-group {{ role }} {{ group }} -n {{ project.name }}
  when: group not in get_groups_with_role.stdout_lines
