---

# Read in application definition
- include_vars: "{{ openshift_resource_definition }}"
  when: openshift_resource_definition is defined

# Process openshift resources
- include: openshift-cluster.yml
  static: false
  with_items: "{{ openshift_clusters | default([]) }}"
  loop_control:
    loop_var: openshift_cluster
  vars:
    oc_cmd_base: >-
      oc
      {% if openshift_connection_certificate_authority is defined %}
      --certificate-authority={{ openshift_connection_certificate_authority | quote }}
      {% endif %}
      {% if openshift_connection_insecure_skip_tls_verify is defined %}
      --insecure-skip-tls-verify={{ openshift_connection_insecure_skip_tls_verify | quote }}
      {% endif %}
      {% if openshift_connection_server is defined %}
      --server={{ openshift_connection_server | quote }}
      {% endif %}
      {% if openshift_connection_token is defined %}
      --token={{ openshift_connection_token | quote }}
      {% endif %}
      {% if openshift_cluster.connection is defined %}
      {% for key, value in openshift_cluster.connection.iteritems() %}
      --{{ key | regex_replace('_', '-') }}={{ value | quote }}
      {% endfor %}
      {% endif %}
  when: >
    # openshift_host_env restricts play run to only process cluster on matching
    # environments, only run if openshift_host_env is not defined or matches.
    openshift_cluster.openshift_host_env is not defined or
    openshift_cluster.openshift_host_env == openshift_master_cluster_public_hostname or
    ( openshift_cluster.openshift_host_env | is_list and
      openshift_master_cluster_public_hostname in openshift_cluster.openshift_host_env
    )
