
- include: cluster-resource-quota.yml
  with_items: "{{ openshift_cluster.cluster_resource_quotas | default([]) }}"
  loop_control:
    loop_var: cluster_resource_quota

- include: openshift-resources.yml
  static: no
  vars:
    openshift_resources: "{{ openshift_cluster.openshift_resources }}"
  when: openshift_cluster.openshift_resources is defined
