## DESCRIPTION
#
# Process template and instantiate objects.
#
# Called from tasks/project.yml
#
## VARIABLES
#
# `project` - project in which to process template with keys:
#   `name` - project name
#
# `template` - template information with keys:
#   `name` - template name
#   `namespace` - template namespace (optional)
#   `parameters` - parameters to pass to template (optional)
#   `no_update` - boolean flag (optional)
#

# FIXME - Add support for template files

- name: Process template
  command: >-
    {{ oc_cmd }} process {{ template.name }} -o json
    -n {{ template.namespace | default(project.name if project is defined else 'openshift') }}
    {% if template.parameters is defined %}
    {% for key, value in template.parameters.iteritems() %}
    -p {{ (key ~ '=' ~ value) | quote }}
    {% endfor %}
    {% endif %}
  changed_when: false
  register: process_template

- name: Template resources
  openshift_provision:
    action: >-
      {{
      item | json_query('metadata.annotations."openshift-provision/action"')
      | default(item.action, true)
      | default(template.action, true)
      | default('apply', true)
      }}
    connection:
      oc_cmd: "{{ oc_cmd }}"
    namespace: "{{ project.name if project is defined else '' }}"
    resource: "{{ item }}"
  with_items: >-
    {{ process_template.stdout | from_json | json_query('items') }}
