## DESCRIPTION
#
# Process template and instantiate objects.
#
# Called from tasks/project.yml
#
## VARIABLES
#
# `project` - project in which to process template with keys:
#   `name` - project name
#
# `template` - template information with keys:
#   `name` - template name
#   `namespace` - template namespace (optional)
#   `parameters` - parameters to pass to template (optional)
#   `no_update` - boolean flag (optional)
#

# FIXME - Figure out a way to detect if apply actually changed anything and
#         set changed_when to match.
- name: Check if template is deployed
  command: >
    {{ oc_cmd }} get all -l template={{ template.name }}
  failed_when: false
  changed_when: false
  register: check_template_deployed
  when: template.no_update | default(False) | bool

- name: Process and apply template
  shell: >
    {{ oc_cmd }} process {{ template.name }}
    -n {{ template.namespace | default(project.name) }}
    {% if template.parameters is defined %}
    {% for key, value in template.parameters.iteritems() %}
    -p {{ (key ~ '=' ~ value) | quote }}
    {% endfor %}
    {% endif %}
    {% if template.overwrite | default(False) | bool %}--overwrite{% endif %}
    | {{ oc_cmd }} apply -n {{ project.name | quote }} -f -
  register: process_template
  when: >-
    not template.no_update|default(False)|bool or
    'No resources found' in check_template_deployed.stdout
