- name: Check if project {{ project.name }} exists
  command: >
    oc get project {{ project.name }} -o json
  changed_when: false
  failed_when: false
  register: get_project

- name: Create project {{ project.name }}
  command: >
    oc adm new-project {{ project.name }}
    --display-name={{ project.display_name | default(project.name) | quote }}
    --description={{ project.description | default('') | quote }}
  when: get_project.rc != 0

# Note:
#
# It should be possible to parse the values for display-name and description
# using: something like:
#
#   get_project.stdout | from_json | json_query('metadata.annotations["openshift.io/display-name"]')
#
# But it appears that the current version of ansible has an incomplete
# implementation of json query that does not understand the square bracket
# notation for extracting an element from an object.
#
# As a workaround we call oc get project again to fetch each of these values.

- name: Get project display name for {{ project.name }}
  command: >
    oc get project {{ project.name }}
    --template '{{ '{{ index .metadata.annotations "openshift.io/display-name" }}' }}'
  changed_when: false
  register: get_project_display_name

- name: Get project description name for {{ project.name }}
  command: >
    oc get project {{ project.name }}
    --template '{{ '{{ index .metadata.annotations "openshift.io/description" }}' }}'
  changed_when: false
  register: get_project_description

- name: Update project metadata for {{ project.name }}
  when: >
    get_project_display_name.stdout != project.display_name | default(project.name) or
    get_project_description.stdout != project.description | default('') or
    ( get_project.rc == 0 and get_project.stdout | from_json | json_query('metadata.labels') | to_yaml != project.labels | to_yaml )
  command: >
    oc patch namespace {{ project.name }}
    -R -p {{ patch | to_json | quote }}
  vars:
    patch:
      metadata:
        annotations:
          "openshift.io/display-name": "{{ project.display_name | default(project.name) }}"
          "openshift.io/description": "{{ project.description | default('') }}"
        labels: "{{ project.labels }}"

- include: project-limit-range.yml
  with_items: "{{ project.limit_ranges | default([]) }}"
  loop_control:
    loop_var: limit_range

- include: project-quota.yml
  with_items: "{{ project.quotas | default([]) }}"
  loop_control:
    loop_var: quota

- include: persistent-volume-claim.yml
  with_items: "{{ project.persistent_volume_claims | default([]) }}"
  loop_control:
    loop_var: persistent_volume_claim

- include: service-account.yml
  with_items: "{{ project.service_accounts | default([]) }}"
  loop_control:
    loop_var: service_account

- name: Get role bindings for project {{ project.name }}
  command: >
    oc get rolebinding -n {{ project.name }} --template '{{
    '{{ range .items }}{{ .roleRef.name }}{{ ":\n  users:\n" }}{{ range .userNames }}  - "{{ . }}"{{ "\n" }}{{ end }}{{ "  groups:\n" }}{{ range .groupNames }}  - "{{ . }}"{{ "\n" }}{{ end }}{{ end }}'
    }}'
  changed_when: false
  failed_when: false
  register: get_role_bindings

# Handle user_to_role
- include: project-user-role-bindings.yml
  with_items: "{{ project.user_to_role | default([]) }}"
  vars:
    current_role_bindings: "{{ get_role_bindings.stdout | from_yaml }}"
  loop_control:
    loop_var: user_role

# Handle group_to_role
- include: project-group-role-bindings.yml
  with_items: "{{ project.group_to_role | default([]) }}"
  vars:
    current_role_bindings: "{{ get_role_bindings.stdout | from_yaml }}"
  loop_control:
    loop_var: group_role

# Handle users in role_bindings
- include: project-user-role-bindings.yml
  static: false
  with_items: "{{ project.role_bindings | default([]) }}"
  when: >
    user_role.users is defined or
    user_role.user is defined
  vars:
    current_role_bindings: "{{ get_role_bindings.stdout | from_yaml }}"
  loop_control:
    loop_var: user_role

# Handle groups in role_bindings
- include: project-group-role-bindings.yml
  static: false
  with_items: "{{ project.role_bindings | default([]) }}"
  when: >
    group_role.groups is defined or
    group_role.group is defined
  vars:
    current_role_bindings: "{{ get_role_bindings.stdout | from_yaml }}"
  loop_control:
    loop_var: group_role
