---
- name: Grant roles on {{ project.name }} to users
  command: >-
    {% if ansible_check_mode %}echo{% endif %}
    {{ oc_cmd }} adm policy -n {{ project.name }} add-role-to-user
    {% if '/' in ocp_role_name %}
    --role-namespace={{ ocp_role_name.split('/')[0] }}
    {{ ocp_role_name.split('/')[1] }}
    {% else %}
    {{ ocp_role_name }}
    {% endif %}
    {{ ocp_user_name }}
    {% if openshift_provision_openshift_version|version_compare('v3.9', '>=') %}
    --rolebinding-name={{ ocp_role_name | replace('/', '-') }}
    {% endif %}
  with_nested:
  - "{{ user_role.roles | default([user_role.role]) }}"
  - "{{ user_role.users | default([user_role.user] if user_role.user is defined else []) }}"
  loop_control:
    loop_var: user_role_ent
  vars:
    ocp_role_name: >-
      {{ user_role_ent[0].name if user_role_ent[0] is mapping else user_role_ent[0] }}
    ocp_user_name: >-
      {{ user_role_ent[1].name if user_role_ent[1] is mapping else user_role_ent[1] }}
    current_role_users_query: "items[?{{ roleref_query }}].userNames[]"
    roleref_query: >-
      {% if '/' in ocp_role_name -%}
      roleRef.namespace=='{{ ocp_role_name.split('/')[0] }}'
      && roleRef.name=='{{ ocp_role_name.split('/')[1] }}'
      {%- else -%}
      roleRef.name=='{{ ocp_role_name }}'
      {%- endif %}
    #'
    current_role_users: >-
      {{ current_role_bindings | json_query(current_role_users_query) }}
  when: ocp_user_name not in current_role_users
  check_mode: false
  register: command
  changed_when: >-
    command | record_change_command(change_record)

- name: Handle remove unlisted users from role bindings
  include_tasks: project-remove-unlisted-user-role-bindings.yml
  static: false
  with_items: "{{ user_role.roles | default([user_role.role]) }}"
  loop_control:
    loop_var: role_ent
  vars:
    ocp_role_name: "{{ role_ent.name if role_ent is mapping else role_ent }}"
    ocp_users: >-
       {{ user_role.users | default([user_role.user] if user_role.user is defined else []) }}
    current_role_users_query: "items[?{{ roleref_query }}].userNames[]"
    roleref_query: >-
      {% if '/' in ocp_role_name -%}
      roleRef.namespace=='{{ ocp_role_name.split('/')[0] }}'
      && roleRef.name=='{{ ocp_role_name.split('/')[1] }}'
      {%- else -%}
      roleRef.name=='{{ ocp_role_name }}'
      {%- endif %}
    #'
    current_role_users: >-
      {{ current_role_bindings | json_query(current_role_users_query) }}
  when: >-
    user_role.remove_unlisted | default(false) | bool or
    user_role.remove_unlisted_users | default(false) | bool
