# DEPRECATED - LimitRange resources should be created through `resources`
---
- name: Deprecation Warning
  fail:
    msg: USING DEPRECATED FEATURE openshift_clusters[*].projects[*].limit_ranges
  ignore_errors: true

- name: Get current {{ limit_range.name }} limit range on {{ project.name }}
  command: >
    {{ oc_cmd }} get limitrange {{ limit_range.name }} -n {{ project.name }} -o json
  check_mode: false
  changed_when: false
  failed_when: false
  register: get_limit_range

- name: Create limit range {{ limit_range.name }} on {{ project.name }}
  shell: >
    echo {{ definition | to_yaml | quote }}
    | {{ oc_cmd }} create -n {{ project.name }} -f -
  vars:
    definition:
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: "{{ limit_range.name }}"
      spec: "{{ limit_range.spec }}"
  when: get_limit_range.rc != 0

- name: Update limit range {{ limit_range.name }} on {{ project.name }}
  command: >
    {{ oc_cmd }} patch limitrange {{ limit_range.name}} -n {{ project.name }}
    -p {{ patch | to_json | quote }}
  vars:
    patch:
      spec: "{{ limit_range.spec }}"
  when: >
    get_limit_range.rc == 0 and
    get_limit_range.stdout | from_json | json_query('spec') | to_yaml != limit_range.spec | to_yaml
