---
- name: >-
    Provision {{ resource.kind }} {{ resource.metadata.name }} in {{ project.name }}
  openshift_provision:
    connection:
      oc_cmd: "{{ oc_cmd }}"
    namespace: "{{ project.name }}"
    resource: "{{ resource }}"
