---
- name: Get pod network for {{ project.name }}
  command: >
    {{ oc_cmd }} get netnamespace {{ project.name | quote }}
    -o 'jsonpath={.netid}'
  changed_when: false
  register: get_pod_network

- name: Get pod network for {{ project.join_pod_network }}
  command: >
    {{ oc_cmd }} get netnamespace {{ project.join_pod_network | quote }}
    -o 'jsonpath={.netid}'
  changed_when: false
  register: get_join_pod_network

- name: Join pod network for {{ project.name }} to {{ project.join_pod_network }}
  command: >
    {{ oc_cmd }} adm pod-network join-projects
    --to={{ project.join_pod_network }}
    {{ project.name }}
  when: get_pod_network.stdout != get_join_pod_network.stdout
