---
- when: resource.metadata.namespace is defined
  include: project-resource-item.yml
  vars:
    project:
      name: "{{ resource.metadata.namespace }}"
  static: false

- when: resource.metadata.namespace is not defined
  include: cluster-resource-item.yml
  static: false
