---
- name: >-
    Provision {{ resource.kind }} {{ resource.metadata.name }}
    {{ resource.metadata.namespace|default('')|regex_replace('^(.)','in \1') }}
  openshift_provision:
    connection:
      oc_cmd: "{{ oc_cmd }}"
    resource: "{{ resource }}"
