- name: Check if service account {{ service_account.name }} in {{ project.name }} has cluster role {{ cluster_role }}
  shell: >
    oc get clusterrolebinding
    --template '{{ '{{ range .items }}{{ .roleRef.name }} {{ range .userNames }}{{ . }} {{ end }}{{ "\n" }}{{ end }}' }}'
    | grep '^{{ cluster_role }}.* system:serviceaccount:{{ project.name }}:{{ service_account.name }} '
  changed_when: false
  failed_when: false
  register: check_service_account_cluster_role_binding

- name: Grant cluster role {{ cluster_role }} to service account {{ service_account.name }} in {{ project.name }}
  command: >
    oc adm policy add-cluster-role-to-user {{ cluster_role }} system:serviceaccount:{{ project.name }}:{{ service_account.name }}
  when: check_service_account_cluster_role_binding.rc != 0
