- name: Get service account {{ service_account.name }} in {{ project.name }}
  command: >
    oc get sa {{ service_account.name }} -n {{ project.name }} -o json
  changed_when: false
  failed_when: false
  register: get_service_account

- name: Create service account {{ service_account.name }} in {{ project.name }}
  when: get_service_account.rc != 0
  command: >
    oc create serviceaccount {{ service_account.name }} -n {{ project.name }}
