- include: user-role-binding.yml
  vars:
    user: "{{ user_role.user }}"
    role: "{{ user_role.role }}"
  when: >
    user_role.user is defined and
    user_role.role is defined

- include: user-role-binding.yml
  with_items: "{{ user_role.roles | default([]) }}"
  vars:
    user: "{{ user_role.user }}"
  when: user_role.user is defined
  loop_control:
    loop_var: role

- include: user-role-binding.yml
  with_items: "{{ user_role.users | default([]) }}"
  vars:
    role: "{{ user_role.role }}"
  when: user_role.role is defined
  loop_control:
    loop_var: user

- include: user-role-binding.yml
  with_nested:
  - "{{ user_role.users | default([]) }}"
  - "{{ user_role.roles | default([]) }}"
  vars:
    user: "{{ user_x_role[0] }}"
    role: "{{ user_x_role[1] }}"
  loop_control:
    loop_var: user_x_role
