---
- hosts: localhost
  connection: local
  vars_files:
  - login-creds.yml
  - vars.yml
  roles:
  - role: openshift-provision
    openshift_resource_path:
    - resources
    openshift_clusters:
    - projects: "{{ lookup('template', 'pipeline-projects.yml') | from_yaml }}"
